### ISSUE TITLE
Error on addint recaptcha

### ISSUE THREAD

**Issue by yupitomets** [VividCortex/angular-recaptcha#101]
I was trying to add reCaptcha on my website inside ng-view part and have a error after added html. Following is the error:

"Error: [$parse:syntax] http://errors.angularjs.org/1.2.16/$parse/syntax?p0=LfDCxYTAAAAAGPBluW2b4Fs8zQ_duE6k7teLCLB&p1=is%20an%20unexpected%20token&p2=2&p3=6LfDCxYTAAAAAGPBluW2b4Fs8zQ_duE6k7teLCLB&p4=LfDCxYTAAAAAGPBluW2b4Fs8zQ_duE6k7teLCLB
t/<@file:///angular.min.js:1:450
$a.prototype.throwError@file://angular.min.js:160:141
$a.prototype.parse@file:////angular.min.js:159:1

**Comment by TheSharpieOne** [comment]
What does your code look like? I'm guessing you did something like `key="6LfDCxYTAAAAAGPBluW2b4Fs8zQ_duE6k7teLCLB"` instead of `key="'6LfDCxYTAAAAAGPBluW2b4Fs8zQ_duE6k7teLCLB'"` (notice the single quotes)

**Comment by yupitomets** [comment]
Yes, you right. Seems now no parse error.

**Comment by yupitomets** [comment]
And one more thing. I've put onSuccess method and receiving huge String like  "03AHJ_VutFlHiGCUCIl_QJOI5I_4SE_FBFuj7gytg34WTQa69Wm0emx5c3dOn0acEs00y-24u3MSyNsElw6aOnwnmOX5bGVdfgsR1jV3wqIhMPy8FIsIaVqgfzlpApikgH7ypR9AbpUfw9ZrtkE4Wzp1Bu9VEZNyPsvbKY2Jsdfg6WxCZXzD0qzalo-piNfNgSGJg2Evi74ysxhIUDGCrjFZHhgkJ7SkMCT6EC"

How this string should be analyzed?

**Comment by TheSharpieOne** [comment]
By Google, as in send it to Google and they will send you back a JSON object with information to whether the string is valid or not and if it is not valid, they it is not valid.
See https://developers.google.com/recaptcha/docs/verify#api-request for more information

To explicitly mention this: This validation of sending the string to Google along with the secrete key is to be done on the backend / server-side, **NOT** by the client.

**Comment by yupitomets** [comment]
Thanks! According to PHP documenation I need to send following data:

$resp = recaptcha_check_answer ($privatekey,
                                $_SERVER["REMOTE_ADDR"],
                                $_POST["recaptcha_challenge_field"],
                                $_POST["recaptcha_response_field"]);
As I understand "recaptcha_response_field" is the responce I am getting via onSucces(), and I have $privateKey. The question is what is recaptcha_challenge_field?

**Comment by TheSharpieOne** [comment]
That documentation looks out-dated. The old reCaptcha used to have challenge and response field, but now there is only response (really, they just combined the two fields into the one).
At the top of the page where you found that, did you see:
![image](https://cloud.githubusercontent.com/assets/664714/12492915/aa4c9ecc-c050-11e5-967e-827fb6253d5b.png)

Take a look at this example: http://stackoverflow.com/a/27439796/1873485 for an example using reCaptcha 2.0

**Comment by yupitomets** [comment]
Thanks so much!
