### ISSUE TITLE
vcRecaptchaService.getResponse() returns empty string after success fires

### ISSUE THREAD

**Issue by thoffman** [VividCortex/angular-recaptcha#115]
My recaptcha loads. I am able to interact with it and validate that I'm human. It then fires the on-success callback. However vcRecaptchaService.getResponse() returns an empty string. I've also tried passing in the widgetId.

NOTE: I'm doing this on localhost. Googles docs claim that localhost should work just fine. Any idea why this is happening?

**Comment by TheSharpieOne** [comment]
In your javascript console, when this happens, is there any error?
In your javascript console, when this happens, what is the value returned when you enter `___grecaptcha_cfg.count` ?

**Comment by thoffman** [comment]
I get a lot these:
Mixed Content: The page at 'https://www.google.com/recaptcha/api2/frame?c=03AHJ_Vuuy7LTIDgmVUR9JN7DOvnK…vcALpLFnR535kWKJt-Y2NUIZxL-5yZM-veUjOv&chr=%5B31%2C41%2C67%5D#dxpfk7vxl214' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/inconsolata/v5/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff'. This request has been blocked; the content must be served over HTTPS.

The count is 2.

**Comment by thoffman** [comment]
I should also note that the only errors I get are the font errors. Which I assume are not ideal but shouldn't prevent this from working.

**Comment by TheSharpieOne** [comment]
Count is 2, meaning there are 2 reCaptcha widgets registered, and chances are, the first one is no longer there anymore and calling it without passing a wigetId attempts to get the first one. In that case, you must call `vcRecaptchaService.getResponse(widgetId)` with the widgetId for the one you want to get the response from. Use the onCreate callback to get the widgetId

Or avoid all of this and you can use the [solution](https://github.com/VividCortex/angular-recaptcha/issues/81#issuecomment-137761725) from #81

**Comment by thoffman** [comment]
Ugh. You are correct. I hadn't noticed a directive was getting called twice. Thank you so much for taking your time to help me.
