### ISSUE TITLE
Provider isn't included in release files

### ISSUE THREAD

**Issue by seanfisher** [VividCortex/angular-recaptcha#119]
I'm seeing the declaration of a [provider in the `service.js`](https://github.com/VividCortex/angular-recaptcha/blob/master/src/service.js#L14) under the `src` folder, but I'm not seeing a corresponding provider under the release. Are the two out of sync, or am I missing something in how to use the provider to configure the code?

```js
app.config(['vcRecaptchaServiceProvider', function (vcRecaptchaServiceProvider) {
    vcRecaptchaServiceProvider.setSiteKey('6LfS...');
}
```

**Comment by seanfisher** [comment]
Sorry, didn't see issue #118 ! Closing this as a duplicate. I guess the answer is, no, they're not in sync.

**Comment by mtrias** [comment]
Yeah, sorry. We have to release these changes. We'll do asap.
