### ISSUE TITLE
Parse Syntax Error

### ISSUE THREAD

**Issue by fer-ri** [VividCortex/angular-recaptcha#12]
Hi

i've got error like this in my console log

```
Error: [$parse:syntax] http://errors.angularjs.org/1.2.16/$parse/syntax?p0=LdtcfUSAAAAAOBJrsfpYCrT3abxR9FzHh8Z9HhD&p1=is%20an%20unexpected%20token&p2=2&p3=6LdtcfUSAAAAAOBJrsfpYCrT3abxR9FzHh8Z9HhD&p4=LdtcfUSAAAAAOBJrsfpYCrT3abxR9FzHh8Z9HhD
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:6:450
    at $a.throwError (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:165:141)
    at $a.parse (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:164:6)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:96:122
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:52:36
    at q (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:7:386)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:51:294)
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:399)
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:416) <div id="form-views" ui-view="" class="ng-scope"> angular.js:9778
```

my HTML

``` html
<div
            vc-recaptcha
            ng-model="formData.captcha"
            tabindex="3"
            theme="clean"
            lang="en"
            key="6LdtcfUSAAAAAOBJrsfpYCrT3abxR9FzHh8Z9HhD"
        ></div>
```

I use it with angular 1.2.16 ..any idea?

Thanks

**Comment by Sutikshan** [comment]
Sorry for commenting on closed issue, but I am getting exact same error, and not able to figure out the cause & answer provided (I am sure, we are doing something silly).
What exactly @ghprod needs to do to fix this error ?
my .html is - 
       <div 
       vc-recaptcha 
       key="model.key"
       theme="light"        
       ></div>

and controller is - 
   $scope.model = {
      key:"xyzkey"
    } 

I also tried providing single quote within key value i.e. key:"'xyzkey'"

**Comment by TheSharpieOne** [comment]
There is no need for single quotes when you are setting the value in the model as such.
If you are using an older version, you may need to wrap model.key in curlies `key="{{model.key}}"`

Can you verify that model.key is within the same scope as the directive?

**Comment by Sutikshan** [comment]
I removed the dependency on scope/controller for key value. and made my .html simpler 

 <div vc-recaptcha key="'6Ld........MYTe1kocbPrB'" theme="light"></div>

my public key is starting from number, could that be problem?

I am using latest directive version of vc-recaptcha (2.2.5), and angular is 1.4.5

Error is 
Error: [$parse:syntax] http://errors.angularjs.org/1.4.5/$parse/syntax?p0=LdsjhQTAAAAAK....SAa…AAAA...MYTe1kocbPrB&p4=LdsjhQT....YTe1kocbPrB
    at Error (native)
    at http://localhost:8080/bower_components/angular/angular.min.js:6:416
    at Object.r.throwError (http://localhost:8080/bower_components/angular/angular.min.js:209:32)
    at Object.r.ast (http://localhost:8080/bower_components/angular/angular.min.js:201:296)
    at Object.rd.compile (http://localhost:8080/bower_components/angular/angular.min.js:210:406)
    at fc.parse (http://localhost:8080/bower_components/angular/angular.min.js:236:376)
    at http://localhost:8080/bower_components/angular/angular.min.js:116:396
    at http://localhost:8080/bower_components/angular/angular.min.js:73:398
    at n (http://localhost:8080/bower_components/angular/angular.min.js:8:3)
    at Y (http://localhost:8080/bower_components/angular/angular.min.js:73:110)(anonymous function) @ angular.js:12416(anonymous function) @ angular.js:9203(anonymous function) @ angular.js:14642m.$eval @ angular.js:15878m.$digest @ angular.js:15689m.$apply @ angular.js:15986g @ angular.js:10511L @ angular.js:10683A.onload @ angular.js:10624

**Comment by TheSharpieOne** [comment]
Some relevant code would help. For the HTML, provide as much as possible, include at least everything within the same controller scope.
For the JS, provide the full controller if possible.
Omit any sensitive information with reasonable dummy values/text as needed.

**Comment by Sutikshan** [comment]
I have login Directive, and I am using angular-recaptcha inside the .html of this directive.
Here is code 

```Javascript
'use strict';
angular.module('amodule').directive('login', [
    function() {
    return {
        restrict: "E",
        templateUrl: "common/partials/login.html",
        controller: "loginCtrl",
        scope:{
        	hideRegister: "=hideRegister" ,
        	key: "=key"
        }
    };
}]);
```

```html
<div class="panel panel-primary well" style="padding:0;">
  <div class="panel-heading panel1-heading" style="text-align: -webkit-center;">
    <div class="panel1-header-text">Login to EhrDiary</div>
  </div>
  <div class="panel-body">
    <form name="loginForm">
      <form-mobile-input isdmodel="user.countrycode" mobilemodel="user.mobile"></form-mobile-input>      
      <div class="form-group">
        <label for="password">Password</label>
        <div class="input-group">
          <div class="input-group-addon">#</div>
          <input type="password" class="form-control" id="password" placeholder="Password" required ng-model="user.password">
        </div>
      </div>
       <div vc-recaptcha key="'6Ldsj....bPrB'" theme="light"></div>
      <div class="checkbox">
        <label>
          <input type="checkbox" ng-model="user.rememberMe">  Remember Me
        </label>            
      </div> 
     
      <div style="text-align:center;">
        <button type="submit" class="btn btn-default btn-raised ehr-save-btn-lg" ng-class="{'btn-success': !loginForm.$invalid}" ng-disabled="loginForm.$invalid" ng-click="login()">Login</button>
        <button type="button" class="btn btn-raised btn-danger ehr-cancel-btn-lg" ng-click="loadRegisterPage()" ng-if="!hideRegister">Register</button>           
      </div>
    </form>
  </div>
</div>
```

```Javascript
'use strict';

angular.module('amodule').controller('loginCtrl', ['$scope', '$location', 'loginService', 'vcRecaptchaService',
  function($scope, $location, loginService, vcRecaptchaService) {

    $scope.user = {
      countrycode: 91,
      rememberMe: false
    };
   
    $scope.login = function() {
      var gCaptchaResponse = vcRecaptchaService.getResponse ();

      if (!gCaptchaResponse) { //if string is empty
        alert("Please resolve the captcha and login!");
        return;
      }

      loginService.login($scope.user.countrycode, $scope.user.mobile, $scope.user.password, $scope.user.rememberMe, gCaptchaResponse).then(
        function(toGoNext) {
          $location.path(toGoNext);
        },
        function(status) {
          if (status.message) {
            alert(status.message);
          } else {
            alert('Invalid mobile number or password!');
            console.log(JSON.stringify(status));
          }
        });
    };

    $scope.loadRegisterPage = function() {
      $location.url("/register");
    };

  }
]);
```

**Comment by AndersBillLinden** [comment]
Is this issue closed without being solved? What I am missing is code for a working solution and also information about whether a key can start with a digit or not.

**Comment by Mudin** [comment]
Hi!

Same error is here.

Did you figure it out?

Mudin

**Comment by TheSharpieOne** [comment]
Things have changed a little and now, how the key is read on the directive level needs to be a model value. You'll have to set the key in scope somewhere and reference the scope variable.
```
<div vc-recaptcha key="myCtrl.Key" theme="light"></div>
```
You can also pass the key in the service provider during the application config function:
```
myApp.config(function(vcRecaptchaServiceProvider){
  vcRecaptchaServiceProvider.setSiteKey('---- YOUR PUBLIC KEY GOES HERE ----')
});
```

Note: the string way on adding it directly to the directive may still work, but it is dependent on the key beginning with an alpha, non-numerical character. This is because when angular see a number, it assumes it is a number and something like `6Ld`... is not a number.

**Comment by Mudin** [comment]
Hi

It is perfectly working now using both way:
<div vc-recaptcha key="vm.key"></div>
and  vcRecaptchaServiceProvider.setSiteKey('---- YOUR PUBLIC KEY GOES HERE ----')

Thank you very much

**Comment by makah** [comment]
I got the same error...  Can you update README with correct tutorial?
