### ISSUE TITLE
vcRecaptchaService.reload() not reseting form validation

### ISSUE THREAD

**Issue by jasonfutch** [VividCortex/angular-recaptcha#120]
Calling vcRecaptchaService.reload() does reset the reCAPTCHA but does not reset form validation.

The notes in your code says the following, but it is not the case.
// reCaptcha will call the same callback provided to the
// create function once this new captcha is resolved.

**Comment by TheSharpieOne** [comment]
Duplicate of #69 fixed in #116. The changes are in master, but not yet released.

**Comment by jasonfutch** [comment]
Thanks! Any ETA on getting that release into the bower version?

**Comment by jasonfutch** [comment]
Never mind.. I forgot you can do the following in bower

"angular-recaptcha": "VividCortex/angular-recaptcha#master"

**Comment by jasonfutch** [comment]
Well crap.. that pulls in the master branch but only the release folder and not the src so I guess I'll have to wait for actual release or branch it off in the mean time.

**Comment by mtrias** [comment]
Sorry about that @jasonfutch we are going to work on this next week.

**Comment by mtrias** [comment]
The release was done, so i believe nothing else neede here? Please reopen otherwise.
