### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by yamaha252** [VividCortex/angular-recaptcha#121]
Can you update your npm package?
https://www.npmjs.com/package/angular-recaptcha

**Comment by mtrias** [comment]
Thanks @yamaha252 we'll work on that next week.

**Comment by yamaha252** [comment]
thanks a lot!

**Comment by mtrias** [comment]
Let's keep it open as a remider though :)

**Comment by iambrosi** [comment]
Version 2.5.0 has been published onto npm

**Comment by fijolekProjects** [comment]
Can you update your npm package once again?

**Comment by mtrias** [comment]
done
