### ISSUE TITLE
on-expire event should execute inside a digest cycle by default?

### ISSUE THREAD

**Issue by rankill** [VividCortex/angular-recaptcha#124]
This repo is awesome, but just one thing, I had to execute a `$scope.$digest();` manually cause my captcha model did not update on captcha expire, should this be action manual or automatic;

**Comment by mtrias** [comment]
This is fixed now. Thanks for reporting it!

**Comment by TheSharpieOne** [comment]
@mtrias The PR is still open

**Comment by mtrias** [comment]
oops. sorry about that. It's merged now.
