### ISSUE TITLE
The need of validating Google reCaptcha on server

### ISSUE THREAD

**Issue by h6784rfg6** [VividCortex/angular-recaptcha#125]
I wonder why I need to extra verify the reCaptcha response.

When injecting it into the form, the captcha should be checked to make the form valid, so, if I won't choose the correct images, the captcha won't be checked -> form won't be able to be submitted. 

And if I though need to validate it on server, how can I use it in the form? I mean, if the validation on server fails, what should I do with my form?

**Comment by jackkum** [comment]
If not check the response to the server side, the reCaptcha is losing its relevance. It is possible to simulate execution of the request to the server, and if not checked reCaptcha, then it is not necessary at all.

If the reCaptcha validation was held in error, you need to give this error and refresh the reCaptcha.

**Comment by h6784rfg6** [comment]
Ok, I am already validating the response on the google server. I close the issue.
