### ISSUE TITLE
Please add lang support

### ISSUE THREAD

**Issue by sebastiandinu** [VividCortex/angular-recaptcha#128]
I have a site that has i18n and I need a way to set the lang of the recaptcha.

**Comment by mtrias** [comment]
This is from the readme docs:

> If you want to force a language, you'll need to add a hl parameter to the script of the reCaptcha API (?onload=onloadCallback&render=explicit&hl=es

Did you try that?

**Comment by sebastiandinu** [comment]
Yes it works. Sorry but didn't know that...
