### ISSUE TITLE
Change recaptcha language

### ISSUE THREAD

**Issue by mlabouardy** [VividCortex/angular-recaptcha#130]
Is there an option to specify the recaptcha language ?

**Comment by iambrosi** [comment]
@mlabouardy You need to use the [`hl` param](https://developers.google.com/recaptcha/docs/display#js_param) when including the _recaptcha API_ from Google.

**Comment by mlabouardy** [comment]
@iambrosi Yes I know, but is there a method to change it directly from vcRecaptchaService ?

**Comment by iambrosi** [comment]
There is no method for changing the language, since it would require re-loading the API script and we don't consider this to be the service's responsibility. You can check #66 for more information.
