### ISSUE TITLE
Captcha Gone after refreshing page.

### ISSUE THREAD

**Issue by PedroMMercado** [VividCortex/angular-recaptcha#133]
Just want to thank you guys for developing this. I'm running into an issue. Everything works great and I have multiple captcha's on the site. However if I hit the refresh button to reload the page. The captcha doesn't load. Doesn't appear that the oncreate function is happening neither. Just a simple refresh and it doesn't work anymore.

**Comment by PedroMMercado** [comment]
I'm an idiot. I was using googles script instead of the one in the docs. Literally on the top of the page.
<script
  src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit"
  async defer
></script>

**Comment by mtrias** [comment]
Cheers!

**Comment by luisfusim** [comment]
Sorry did you put it on the index.html or in the view.html (register for example) ?
