### ISSUE TITLE
Is it possible to use this directive without server code?

### ISSUE THREAD

**Issue by zinotinder** [VividCortex/angular-recaptcha#134]
I just need confirmation. I submit data to third party rest api directly from javascript. So is it possible to implement captcha withouth server code?

**Comment by mtrias** [comment]
TL;DR: Not possible, nor it would make sense to.

Recaptcha's purpose is to prevent robots to reach your servers, so, it wouldn't make sense to validate the recaptcha submission other than right in the server you want to protect.

If you don't have a server to protect then you don't need recaptcha.

If you are dealing with a 3rd party api that is open to the internet, then i'd say is their duty to provide the means to prevent bots.

**Comment by zinotinder** [comment]
Hi thanks for your response. I understand that there is a need for server in order to protect request.
But is it possible to implement this directive just to prevent form submit if captcha is not solved? 
Lets say that I don't care about check on server I just want that user must solve it in order to submit data.

**Comment by TheSharpieOne** [comment]
Yes, you can do as the readme says to implement it. Note that doing it as you describe would only hinder your real users and not prevent spam/automated submissions.
