### ISSUE TITLE
Form validation on fallback mode

### ISSUE THREAD

**Issue by ripfire44** [VividCortex/angular-recaptcha#137]
The form validation on recaptcha works just fine on most modern browsers. However, I noticed that when it's using the fallback option, it's returning a form validation error for recaptcha when the user copy & paste into the input.

**Comment by ripfire44** [comment]
Did a little bit more debugging and I found out that with the fallback option, it's not calling the `callback` from the `POST`. I'm guessing this is by design. I'll just have to figure another way around in the meantime.

**Comment by jrauschenbusch** [comment]
This ticket is a duplicate of https://github.com/VividCortex/angular-recaptcha/issues/46. By applying the discussed patch the fallback mode works fine.

**Comment by mtrias** [comment]
Closing as duplicate then. Please reopen if i'm wrong.
