### ISSUE TITLE
Prevent throwNoKeyException() when loading from database?

### ISSUE THREAD

**Issue by raydawg2000** [VividCortex/angular-recaptcha#140]
So i load my "key" value into the scope from the result of an Ajax request.  Im assuming since the "key" value isn't immediately available upon recaptcha creation, this is why the exception gets thrown.  What is the solution to preventing this from happening other than just modifying the source to not throw the exception.

The recaptcha works fine, but every page that loads throws that nasty console error along with a full stacktrace

**Comment by TheSharpieOne** [comment]
Try throwing an `ngIf` on the element with `vcRecaptcha`. Make the if statement a condition requiring your key to be present to return true. Something like
```
<div ng-if="myCtrl.myKey" vc-recaptcha key="myCtrl.mykey"></div>
```
This should prevent the directive from running until the key is available.

**Comment by raydawg2000** [comment]
Works great thanks!
