### ISSUE TITLE
Any parameter / switch to change languages ?

### ISSUE THREAD

**Issue by albertytau** [VividCortex/angular-recaptcha#141]
When I programme in PHP, i use 

`<script src="//www.google.com/recaptcha/api.js?hl=EN" async defer></script>`

to load the language for the recaptcha, is there any option / switch for angular-recptcha to change languages ?

**Comment by russellhoy** [comment]
It looks like you have to specify the language in the script src, so you'd have to do something like:

<script src="//www.google.com/recaptcha/api.js?hl={{language}}" async defer></script>

**Comment by reduardo7** [comment]
Maybe this problem is solved with https://github.com/VividCortex/angular-recaptcha/issues/161

**Comment by mtrias** [comment]
It looks like the issue was resolved. Please reopen otherwise
