### ISSUE TITLE
Readme section on testing

### ISSUE THREAD

**Issue by molerat619** [VividCortex/angular-recaptcha#143]
Hi there!
 
I am having a hard time testing a controller that uses angular-recaptcha right now. I am pretty sure I am not the only one, so a small example in the documentation would be pretty cool.

**Comment by TheSharpieOne** [comment]
As a unit testing methodology, you only test the code you write. You should create a simple mock to injection into your test which replaces the actual angular-recaptcha. This mock would expose the same signature and methods as the original but calling these methods would usually call a spy and return some expected data. You'd then test that your code called the third party code by checking that the spy was called as you expected it to be.
The only thing this project could do to help would be to give the mock that would be injected for testing. If the mock was provided, then something in the readme would be appropriate, without it you would just test your code as normal, mocking out dependencies.

**Comment by molerat619** [comment]
Thanks for your reply. I understand. Since I'm new to testing, I don't know if modules like this one usually put a mock-section in their readmes. If yes, I guess that'd be cool :)
