### ISSUE TITLE
issue on mobile or tablet device

### ISSUE THREAD

**Issue by osamabari** [VividCortex/angular-recaptcha#149]
when popup is open and user select a image then images automatically changed every time.
its happen when you try it couples of time first time is working fine.
i sharing live link
http://biz.forkspot.com/add_business

**Comment by TheSharpieOne** [comment]
This sounds like recaptcha is working correctly. This is one of the few verification methods used if the automatic human verification is not confident enough to determine if the user is a bit or not.

**Comment by mtrias** [comment]
This sounds like a wontfix. Please reopen if i'm wrong
