### ISSUE TITLE
POST Request not working

### ISSUE THREAD

**Issue by marciogurka** [VividCortex/angular-recaptcha#150]
I had some issues when I was sending the POST Request like says in the documentation. I don't know what I was doing, but when I tried to send a GET Request it works fine! I sent a GET Request like this:

`$http.get(https://www.google.com/recaptcha/api/siteverify?secret=your_secret&response=response_string&remoteip=user_ip_address).then(function(response){
...
})`

**Comment by TheSharpieOne** [comment]
There is no documentation in this project instructing anyone to do what you are trying. You should be doing that from the server, not the client. And the server aspects is outside of this project. Depending on which backend you are using (java, node, Ruby, .NET) there are libraries which can and help and make validating the recaptcha response.

**Comment by marciogurka** [comment]
Oh, I see, thanks a lot!
