### ISSUE TITLE
error when parsing the public key

### ISSUE THREAD

**Issue by tuytuy** [VividCortex/angular-recaptcha#152]
I get this error when i try to load my page. I used the Site key provided by google but it just doesnt work ...

Syntax Error: Token 'MY KEY HERE WITHOUT THE FIRST CHARACTER' is an unexpected token at column 2 of the expression [My KEY WITHOUT HERE] starting at [MY KEY WITHOUT THE FRSIT CHARACTER].

**Comment by tuytuy** [comment]
The problem wast hat i forgot the second quotes so if anyone gets this error:

in the HTML the key should be place inside double quotes then single quotes, as follow:

key= **" '** 6fsdqyQTAAAAAL3f84541LAXY5E_GfdsqRGfdsqfeI **' "**

**Comment by j-gao** [comment]
@tuytuy Thanks for sharing the solution! Do you know why we need to have these two layers of double and single quotes?
