### ISSUE TITLE
IE Script5: Access Denied

### ISSUE THREAD

**Issue by vinayraghavendra** [VividCortex/angular-recaptcha#157]
Hi

I am getting strange error in IE, please refer the screenshot.

Html:
`<div data-ng-controller="recaptchaController">
<div
                data-vc-recaptcha
                data-theme="'light'"
                data-key="model.key"
                data-on-create="setWidgetId(widgetId)"
                data-on-success="setResponse(response)"
                data-on-expire="cbExpiration()"
            ></div>
<input id="reCaptchaHiddenResponse" name="reCaptchaHiddenResponse" type="hidden" data-ng-value="response"/>
</div>`

Controller:

`app.controller('recaptchaController',['$scope','vcRecaptchaService','commonService', function ($scope, vcRecaptchaService,commonService) {
                $scope.response = null;
                $scope.widgetId = null;
                $scope.isError = false;
                $scope.model = {
                    key: '6Lf-sgdfgdfgdfgdfgdfgdfgdfgfdgfgfgdfgf'
                };
                $scope.setResponse = function (response) {
                    $scope.response = response;
                    $scope.isError = false;
                    $("#reCaptchaErrorSpan").html("").hide();
                };
                $scope.setWidgetId = function (widgetId) {
                    $scope.widgetId = widgetId;
                };
                $scope.cbExpiration = function() {
                    $scope.response = null;
                    $scope.isError = false;
                    $("#reCaptchaErrorSpan").html("").hide();
                    vcRecaptchaService.reload($scope.widgetId);
                 };

```
        }]);`
```

please help me to resolve this

![recatcha](https://cloud.githubusercontent.com/assets/6661572/17585671/c6f4b7b0-5fda-11e6-9d53-1f577ee5ffa1.PNG)

**Comment by TheSharpieOne** [comment]
The error is happening in reCaptcha's code, it would be best to file an issue with them.
