### ISSUE TITLE
two captcha on single page... second captcha  reseting(refresh) issue

### ISSUE THREAD

**Issue by anjumkhalid** [VividCortex/angular-recaptcha#166]

**Comment by anjumkhalid** [comment]
i have  2 form on single page both have captcha.Both form have different  controller. when second form submit captcha not resetting.

**Comment by TheSharpieOne** [comment]
With multiple captchas on the page, you will need to pass the widgetId of the captcha you want to reset to the reload method.

**Comment by anjumkhalid** [comment]
thanks. it worked
