### ISSUE TITLE
Angular 1.5.x

### ISSUE THREAD

**Issue by noprobz09** [VividCortex/angular-recaptcha#168]
How to implement this on angular 1.5.x version. I tried it using the steps but it does not work. Is there specific steps to work it on the higher version of Angular?

**Comment by mtrias** [comment]
I'm using it with angular 1.5 with no issues. Can you clarify what do you mean when you say it does not work?

**Comment by noprobz09** [comment]
Oh Sorry for bothering, I manage to solved the problem. It just happen that I called 2 https://www.google.com/recaptcha/api.js on the body and I commented the other script and it works like a charm. I appreaciated your work :)
