### ISSUE TITLE
onCreate callback does not return the widgetId parameter

### ISSUE THREAD

**Issue by honkskillet** [VividCortex/angular-recaptcha#169]
Hello,
I've been trying to get the callback for onCreate to return the widgetId with no luck.  When I dig into the service I can see that the widgetId has been created but it doesn't make it back to the callback function.  Here is a plnkr that demonstrates the issue. (Look at the console logs.)
[plnkr](http://plnkr.co/edit/ZbKMlOFw28e32iGCDq8v?p=preview)

**Comment by TheSharpieOne** [comment]
widgetId is the key for the injection into the callback. Like `on-create="create(widgetId)"`

**Comment by honkskillet** [comment]
I'm not sure I get what you are saying.  Isn't widgetId provided by the service?  In my plnkr I add a console.log to the service and you can see that each new widget gets assigned it's own id.

**Comment by TheSharpieOne** [comment]
Change `on-create="create(id)"` to `on-create="create(widgetId)"`
It has to be called `widgetId` in the expression which appears as an attribute value in the html. You can call it whatever you want in the actual function.

**Comment by TheSharpieOne** [comment]
BONUS POST!
To go into more details (previously I was commenting from a mobile phone which makes it hard to go into details), [This line](https://github.com/VividCortex/angular-recaptcha/blob/master/src/directive.js#L59) where the callback is trigged passes an object with the key `widgetId`. This object extends the local scope in which the function is executed to have a variable `widgetId` which is the value provided on that line. This means you need to use the variable `widgetId` which is in scope for it to be passed to your callback. You are currently you `id`, which tries to pull `id` out of the scope. `id` doesn't exist, so it is undefined when passed to the callback.

See the last part in the bullet for`& or &attr` within https://docs.angularjs.org/api/ng/service/$compile#-scope- section

**Comment by honkskillet** [comment]
@TheSharpieOne Thank you
