### ISSUE TITLE
release code out dated (missing lang feature)

### ISSUE THREAD

**Issue by reduardo7** [VividCortex/angular-recaptcha#173]
I agree with https://github.com/VividCortex/angular-recaptcha/pull/170#issuecomment-263983842, but now the `release` dir don't contain the minified code. Should I make this missing commit? Or you should do it?

From already thank you very much!

**Comment by iambrosi** [comment]
@reduardo7 Sorry for this. I'll fix it.

**Comment by reduardo7** [comment]
@iambrosi Thank you!

**Comment by iambrosi** [comment]
The new release [3.2.1](https://github.com/VividCortex/angular-recaptcha/releases/tag/3.2.1) is now available.
