### ISSUE TITLE
I can't use TypeError: vcRecaptchaServiceProvider.setLang is not a function

### ISSUE THREAD

**Issue by gioknx** [VividCortex/angular-recaptcha#177]
In my config, when I try to set the language, it throws me this error. I can't understand why, since this function is described in the main page of the lib.

**Comment by TheSharpieOne** [comment]
What version are you using? Only the latest release has setLang. Also, can you post your code?

**Comment by gioknx** [comment]
Oh, I was using the release from NPM, which is kinda old. Switched to the manual version and it worked! Thanks

**Comment by TheSharpieOne** [comment]
@iambrosi or @mtrias npm currently has 3.2.0 which has the old dist files. Can 3.2.1 be published to npm?

**Comment by iambrosi** [comment]
@TheSharpieOne done
