### ISSUE TITLE
Recaptcha doesn't show in chrome

### ISSUE THREAD

**Issue by AlanNasario** [VividCortex/angular-recaptcha#182]
I am currently using version 4.0.1, it works fine in edge and explorer, but the widget doesn't show in chrome. 
I also tried the demo on http://vividcortex.github.io/angular-recaptcha/ which seems to work fine except for chrome.

**Comment by TheSharpieOne** [comment]
Reinstall Chrome and/or Windows and try again. Also, consider reporting this to the Google reCaptcha team https://groups.google.com/forum/#!forum/recaptcha as this library wraps reCatpcha, any rendering issues would be reCaptcha itself.

**Comment by AlanNasario** [comment]
I retested http://vividcortex.github.io/angular-recaptcha/ in Chrome, Firefox, Edge and Explorer on multiple computers, and the widget only appeared using Explorer.

**Comment by Cossens** [comment]
I have observed the same behaviour as AlanNasario accessing the demo site in Chrome 56.0.2924.76

**Comment by AlanNasario** [comment]
Cossens did you get it working?

**Comment by Cossens** [comment]
No sorry, I haven't been able to get the demo site going in chrome. I'm just investigating this library as an option for a project. I haven't tried it on my site yet.

**Comment by TheSharpieOne** [comment]
Can you send a screenshot, browser frame and all? There may be a blocked script. Since Chrome is more secure than Internet Explorer / edge, it may be blocking some assets

**Comment by AlanNasario** [comment]
Both look similar, 
![firefox](https://cloud.githubusercontent.com/assets/8241585/22573299/2fa1377c-ea0d-11e6-886a-9b1e029b1d86.PNG)
and both have an error ```
TypeError: $document.get is not a function
    at Constructor.provider.$get (angular-recaptcha.js:152)
```
but i'm not sure if this will help with my 4.0.1 project

**Comment by TheSharpieOne** [comment]
It's interesting that I don't get that, but it appears to be related to jquery not being on the page when angular is loaded. It's already fixed but need to be released. Once it's released, give it another try.

**Comment by AlanNasario** [comment]
On my project the widget appears when the api call is in the head, but as soon as the page is refreshed it fails to reload the widget

**Comment by Cossens** [comment]
Hey @AlanNasario, I used v4.0.0 (previous release) in my project and it's working in chrome. You could consider this solution until this issue is resolved.

**Comment by iambrosi** [comment]
@AlanNasario The latest version(v4.0.2) has been released, which includes the fix mentioned by @TheSharpieOne. Can you please try with the new version and see if the error was resolved?

@AlanNasario @Cossens I haven't been able to reproduce the error you mentioned with the demo site. Maybe your browser is loading a cached version of the previous v4.0.1?

**Comment by iambrosi** [comment]
I forgot to build the release for v4.0.2 😠 A new version v4.0.3 has been released

**Comment by Cossens** [comment]
@iambrosi I am retrieving an older version. 

![image](https://cloud.githubusercontent.com/assets/5078408/22581047/11e059f4-ea42-11e6-80b5-d6049cb39f72.png)

Inspecting the source shows it was built on the 18th of Jan.

Could it be that you need to purge the CDN? The same version shows up in chrome when I disable cache and when I viewed the site in Edge for the first time.

**Comment by mtrias** [comment]
Doh ... Github's CDN cache [is permanent by url](https://github.com/rgrove/rawgit/blob/master/FAQ.md#whats-the-difference-between-rawgitcom-and-cdnrawgitcom-urls).

I just updated the demo site to use rawgit and the latest AngularJS version. Could you please retry?

**Comment by Cossens** [comment]
Perfect! Well done team.

![image](https://cloud.githubusercontent.com/assets/5078408/22604185/49c8d9fa-eaaf-11e6-8685-dc1729c524a5.png)

**Comment by mtrias** [comment]
Thanks for your help everyone!

**Comment by AlanNasario** [comment]
I got 4.0.3, I put in <script src="http://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit" async defer></script> like on the fixed demo page and it works.
