### ISSUE TITLE
captcha is not loading on page reload/refresh 

### ISSUE THREAD

**Issue by iamvasim786** [VividCortex/angular-recaptcha#183]
I have single page application, captcha load on first time when application load but if i am reloading the page then it not work.
this is my html page where i'm include captcha -
```
<div vc-recaptcha  key="'xxxxxxxx'"
   ng-model="gRecaptchaResponse"></div>
```

**Comment by iamvasim786** [comment]
Now, it is working.
i am including 
```<script src="https://www.google.com/recaptcha/api.js></script>``` 
instead of ```<script src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit" async defer></script>```

**Comment by TheSharpieOne** [comment]
With the latest version, you do not need that script at all.
