### ISSUE TITLE
Was 4.0.3 published to npm?

### ISSUE THREAD

**Issue by bluetech** [VividCortex/angular-recaptcha#184]
Hi, from the commits it seems like 4.0.2 was a bad release, and 4.0.3 fixed that. However only 4.0.2 was published to npm: https://www.npmjs.com/package/angular-recaptcha

Is it OK to use 4.0.2 or should 4.0.3 be published?

Thanks.

**Comment by mtrias** [comment]
@iambrosi would [something like this](https://github.com/geddski/grunt-release) be useful to automate the release process?

**Comment by iambrosi** [comment]
Version 4.0.3 has been published

**Comment by iambrosi** [comment]
@mtrias It could be useful. We would need to replace _grunt-bump_ by _grunt-release_.
