### ISSUE TITLE
Cannot contact reCAPTCHA. Check your connection and try again.

### ISSUE THREAD

**Issue by Mr-Anonymous** [VividCortex/angular-recaptcha#185]
I am using this angular plugin with Google Invisible reCaptcha using one of the suggestions from here. Occasionally I get this error message "Cannot contact reCAPTCHA. Check your connection and try again." when clicking on the Button that has the Invisible reCaptcha enabled. When I refresh the page, it seems to work. When I try the same from other browser at the same time, it works. It happened once in google chrome and a few times in Safari.

Is this issue related to Google's reCaptcha or plugin or something else? Has anyone experienced this issue before?

I am using the current version of this plugin on Angular 1.4.

Thanks,
Neel.

**Comment by Mr-Anonymous** [comment]
After digging into this more, I found the following error from Safari console:
```
Unsafe JavaScript attempt to access frame with URL http://example.com.au/#/login from frame with URL https://www.google.com/recaptcha/api2/anchor?k=6LfvThUUAADEExfCGDmbT28ISznd1YJSSW39ab&co=aHR0SdsdWWYi5BcHBzZXNzbWAAsssA.&hl=en&type=submit&v=r2017020s11221236&size=invisible&cb=m502229m5o6. Domains, protocols and ports must match.
```
This error only happens from Safari browser in Windows where as it works fine in other browser including Safari in Mac. Does it point to anything? Does it mean, I need to have `https` protocol for my origin site for this to work? I dont understand why the error only happens with this 1 browser.

**Comment by TheSharpieOne** [comment]
Safari doesn't have a browser for Windows anymore. The thing you reference is not supported by anyone anywhere.

**Comment by Mr-Anonymous** [comment]
Thanks for pointing that out @TheSharpieOne. That makes sense. The Safari version I have in windows is v5.1.7 whereas my Mac has 10.0.3. However, what is interesting is, I was able to login to my account in 99Designs website which also uses the latest invisible recaptcha for login page. I didn't have this error when logging in using Safari windows. Anyhow, since it is obsolete, I guess I will worry more only if the same issue happens in another browser.

Thanks again for your comment. It helped.

**Comment by priyati** [comment]
Hi, I am facing this issue on my localhost. And I am using google chrome as a browser. Do you have any idea why this error shows up? and any solution you know to fix this. My application is running in angular js.
