### ISSUE TITLE
Changing language raise an error 

### ISSUE THREAD

**Issue by picolo74** [VividCortex/angular-recaptcha#191]
if i change the language  i have this error :

Uncaught TypeError: Cannot set property 'tabindex' of undefined
    at Rp (recaptcha__en.js:formatted:11491)
    at Ip.f.hk (recaptcha__en.js:formatted:11533)
    at nm.<anonymous> (recaptcha__en.js:formatted:7956)
    at rd (recaptcha__en.js:formatted:1222)
    at nd (recaptcha__en.js:formatted:1259)
    at recaptcha__en.js:formatted:1160

https://plnkr.co/edit/3KxzSsAonbli03FpjJf4?p=preview

**Comment by TheCodeDestroyer** [comment]
Same here...

**Comment by shopen21** [comment]
I experience exactly the same error when using lang different from 'en' (i.e. 'uk'). I specify lang in config (via provider or via directive attribute)

**Comment by wickY26** [comment]
We have same issue as well.
As a temporary fix do not set lang for directive because problem is getting recaptcha__xx.js where xx is language code. 

When captcha starts it gets recaptcha__xx.js then depends on your lang selection it gets another recaptcha__xx.js. So if xx' are not same problem occurs...

**Comment by peteryoung7788** [comment]
Same problem here... When will this be fixed?

**Comment by fredssbr** [comment]
The only way it's working now is when we do not set lang for the directive.

**Comment by PaulBrimley** [comment]
I add my vote to this issue

**Comment by thewarpaint** [comment]
@picolo74 can you please add your OS/browser version to the issue? I cannot reproduce it using your Plunker in macOS Sierra and Chrome 58/Firefox 47.

**Comment by picolo74** [comment]
Hi, i can't reproduce anymore, google may have update/fix recaptcha.

**Comment by thewarpaint** [comment]
@picolo74 Thanks!
