### ISSUE TITLE
Cannot reload recaptcha 

### ISSUE THREAD

**Issue by Tarek-AbdelMaqsoud** [VividCortex/angular-recaptcha#194]
**Hello,**
When i try to reload the recaptcha, it gives me the following error

**Invalid ReCAPTCHA client id:**

here is my code:
`<script src="https://www.google.com/recaptcha/api.js?hl=ar&onload=vcRecaptchaApiLoaded&render=explicit" async defer></script>`

`<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-recaptcha/4.0.4/angular-recaptcha.js" async defer></script>`

` <div id="captcha_container" vc-recaptcha key="CaptchaKey" on-expire="CaptchaExpired()" on-success="setResponse(response)" on-create="onWidgetCreate(widgetId)"></div>`

and here is my angular code
`$scope.CaptchaExpired = function () {
            vcRecaptchaService.reload($scope.widgetId);
        };

        $scope.onWidgetCreate = function (_widgetId) {
            $scope.widgetId = _widgetId;
        };
        $scope.setResponse = function (response) {
            if (response !== null && response !== undefined && response !== '') {
                $scope.validCaptcha = true;
            }
        };`

**Comment by TheSharpieOne** [comment]
is `CaptchaKey` a placeholder in your example, or is that literally the code you have and use?

**Comment by Tarek-AbdelMaqsoud** [comment]
Actually it is just a placeholder ..

**Comment by Tarek-AbdelMaqsoud** [comment]
Well, seems it was an old bug, as i just solved it by upgrading to the latest version .. Thanks :)
