### ISSUE TITLE
Update Latest Release to be 4.0.4

### ISSUE THREAD

**Issue by spengilley** [VividCortex/angular-recaptcha#199]
I recently pulled down 4.0.0 and couldn't get reCaptcha to appear. Only realised I didn't have latest when I checked source of the demo page and saw it was using 4.0.4. Although there is a tag for 4.0.4 it isn't marked as latest release
![screen shot 2017-04-19 at 13 56 13](https://cloud.githubusercontent.com/assets/749260/25181044/1bfa24b4-2508-11e7-84a0-c32066a930e5.png)

**Comment by mtrias** [comment]
The release is actually there
![image](https://cl.ly/2C402w352K2X/download/Screen%20Recording%202017-04-19%20at%2011.57%20AM.gif)

[npm](https://www.npmjs.com/package/angular-recaptcha) has it too
![image](https://cloud.githubusercontent.com/assets/801752/25186799/9e27c9de-24f7-11e7-99f7-728a08e19a0c.png)

**Comment by TheSharpieOne** [comment]
@mtrias click "Draft a new release" and select 4.0.4 from the version dropdown list and publish the release. It makes it the "Latest Release" on github's release page.

**Comment by mtrias** [comment]
Sure, it's done.

So, out of curiosity, How is this latest release important for people when we have semver, and both npm and bower bring the latest version available?
