### ISSUE TITLE
Mean.js Recaptcha click ie11 errors with Object doesn't support property or method 'Symbol'

### ISSUE THREAD

**Issue by GeetaAhuja** [VividCortex/angular-recaptcha#209]
SCRIPT438: Object doesn't support property or method 'Symbol'
recaptcha__en.js (4,189)

**Comment by TheSharpieOne** [comment]
That is best reported to Google's recaptcha team as it is their script.

**Comment by GeetaAhuja** [comment]
There was an item defined with id Symbol in one our svg's so symbol was coming up as svgpathelement instead of function
