### ISSUE TITLE
How does the library react to a robot when using size=invisible ?

### ISSUE THREAD

**Issue by little-boy** [VividCortex/angular-recaptcha#218]
Hi,

I am currently implementing your library and i managed to make it works with the option size=invisible.

I would like to know what happens if a user is considered as a robot. 

1. Is there a fallback ? A way for the user to prove that he is not a robot
2. If so, is there a way to spoof myself as a robot to see reproduce and ensure my website behave well in that case ?

**Comment by TheSharpieOne** [comment]
This library allows you to more easily use Google's reCaptcha by integrating that into angular. As for how it handles robots, that is up to Google's reCaptcha. Currently, with the invisible reCaptcha, it will open a popover-like box and ask the user to answer/complete a challenge. These challenges vary but can be something like selecting all of the images which have cars in them.
As for forcing the challenge, I am not sure how to do that. I know Google reCaptcha has special keys for testing which will always pass verification, but I don't know about the other. The best place for this question would be Google reCaptcha's fourms.

**Comment by little-boy** [comment]
Thank you for you answer.
