### ISSUE TITLE
recaptcha.render is not a function

### ISSUE THREAD

**Issue by williambueti** [VividCortex/angular-recaptcha#224]
Now that Google is loading a second library for reCaptcha, if the angular-recaptcha library is cached in the browser it loads and tries to render before Google's second library finishes, resulting in: https://www.screencast.com/t/NERK8upzoq

**Comment by williambueti** [comment]
Network sequence of scripts: https://www.screencast.com/t/OLnZo27pV88

**Comment by tony-kaplan** [comment]
yeah, I have same issue, very urgent

**Comment by rinconjc** [comment]
Experiencing the same issue!.... Any workaround? anyone?

**Comment by muthukrishk** [comment]
@tony-kaplan could you please explain from which line the above include should be removed ? I can see a couple of imports

**Comment by williambueti** [comment]
So what I believe @tony-kaplan is reffering to is if in your html you include the above line, it should be removed, because the angular-recaptcha library already makes a call to load this.

Please correct me if I'm wrong.

**Comment by iambrosi** [comment]
@williambueti I just submitted a PR as an attempt to fix this issue. Would you please check if you can reproduce the issue with the code from that PR?

**Comment by AbdallaANasser** [comment]
I got this error again in version `1.0.4`. 
```
TypeError: recaptcha.render is not a function
    at angular-recaptcha.js:199
```

**Comment by 2madera** [comment]
Just upgrade the version of plugin and be happy!

**Comment by japenagoss** [comment]
> I found the solution:
> 
> Upgrade to latest version and remove below manual include since version 4.0 they alr auto import the library.
> 
> `<script src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit" async defer></script>`

great solution, thanks
