### ISSUE TITLE
Update Latest Release

### ISSUE THREAD

**Issue by pedrolopesme** [VividCortex/angular-recaptcha#228]
Hey VividCortex,

The latest release on your Releases page is pointing to v.4.1.0. Can you please point it to 4.1.5? 

![image](https://user-images.githubusercontent.com/19935/40431428-ccc83344-5e7d-11e8-9996-32f8806bd6d0.png)

**Comment by TheSharpieOne** [comment]
That is just github, it doesn't actually affect anything (unless you are using GitHub's API to get a list of releases... maybe that is how bower works?).
npm had the correct version https://www.npmjs.com/package/angular-recaptcha

Anyway, the latest one has been marked as such. Closing.
