### ISSUE TITLE
The error callback is not present for the plugin

### ISSUE THREAD

**Issue by nikhilnagaraju** [VividCortex/angular-recaptcha#229]
The error callback as mentioned in [Google ReCaptcha (V2) documentation](https://developers.google.com/recaptcha/docs/invisible#config) doesn't exist with this library, will it be added or how can someone override the default behaviour (which currently shows a alert dialogue)

**Comment by TheSharpieOne** [comment]
I don't think the error callback existed when this library was made. The library needs to be updated to expose it in a similar way to the regular callback and expire callback.
