### ISSUE TITLE
On load event not triggering

### ISSUE THREAD

**Issue by Shamilik** [VividCortex/angular-recaptcha#24]
On load event not triggering after page load, so reCAPTCHA not loading.

Im loading scripts at the bottom of page in this order:
angular.min.js?v=1.3.7
angular-route.min.js?v=1.3.7
angular-recaptcha.min.js?v=2.0.0
recaptcha/api.js?onload=ngRecapthaApiLoaded&render=explicit&hl=en
ui-bootstrap.min.js?v=0.12.0

**Comment by rluders** [comment]
https://github.com/VividCortex/angular-recaptcha/issues/93
