### ISSUE TITLE
Get sitekey via http request

### ISSUE THREAD

**Issue by paulinhps** [VividCortex/angular-recaptcha#246]
Hello!

I would like to make a contribution to the solution. Provide the option to obtain the sitekey via http request.
I have already implemented just want authorization and a branch to make a pull request.

Thanks!

Paulo Henrique Santana
paulinhps@gmail.com

**Comment by TheSharpieOne** [comment]
IMHO such a feature should remain in the user's code. As the code currently is, it is possible to perform a network request to load the key and then provide the key directly to the directive. You can conditionally load the directive via ngIf to prevent the directive from running before the key is loaded.

**Comment by iambrosi** [comment]
I agree 100% with @TheSharpieOne. Loading the site key from an external source is not this library's responsibility.
