### ISSUE TITLE
Callback doesn't accept variables sent from the html

### ISSUE THREAD

**Issue by PLEEROCK** [VividCortex/angular-recaptcha#27]
I have user variable in my scope, and use it like this in my html:

```javascript
on-success="setCaptcha(user, response)"
```
But in `setCaptcha` user in undefined, and response is OK.
Excepted user to be an object that I've passed.

on what scope does setCaptcha runs? It should run on the same scope as user (me) on.
and btw why did you decide to remove ng-model, and use callbacks instead? I think using it with ngModel was better,

**Comment by PLEEROCK** [comment]
take my words back, it works correctly. but still, why did you remove `ng-model` ?

**Comment by PLEEROCK** [comment]
And also, I need to call $apply by myself to update variable, is it a correct behaviour?

$scope.setUserCaptcha = function (user, response) {
            user.captcha = response;
            $scope.$apply();
};

**Comment by TheSharpieOne** [comment]
I'd say the `ngModel` not getting set and having to `$apply()` are core things that everyone would need to do and should be implemented as part of the project.

I mean, would you rather have your function and pass in `user` so you can put `response` as `user.captcha` (and `$apply()`) or would simple set `ng-model="user.captcha"` on your element in the view?

**Comment by TheSharpieOne** [comment]
#31, now merged, adds back the `ngModel` feature as well as `$apply()`ing so the callback will not need to manually run `$apply()`
