### ISSUE TITLE
null response

### ISSUE THREAD

**Issue by dalexandrov** [VividCortex/angular-recaptcha#38]
Hello,
if i just copy paste the example and add my public key I alway get
"sending the captcha response to the server null"

what may be the problem?

**Comment by TheSharpieOne** [comment]
The demo only solves the front-end, you will still need a back-end to validate the recaptcha.
[Here](https://github.com/VividCortex/angular-recaptcha/blob/4924523a5bbf1e5a138e4ef42f3389beb2f672e4/demo/usage.html#L53) is where the message you are seeing is coming from.
You can see [above that](https://github.com/VividCortex/angular-recaptcha/blob/4924523a5bbf1e5a138e4ef42f3389beb2f672e4/demo/usage.html#L49) it tells you that you need to implement that back-end.  Depending on which back-end you are using, you may be able to find a pre-made solution for that.

**Comment by mtrias** [comment]
If you are workin
