### ISSUE TITLE
on-create gives me widgetId = 0

### ISSUE THREAD

**Issue by pambuk** [VividCortex/angular-recaptcha#39]
As the title says, onCreate returns 0 for widgetId

**Comment by TheSharpieOne** [comment]
What does you onCreate function look like.  Also what does it look like in the view / on the directive?

The code simply passes the value from [`grecaptcha.render(...)`](https://developers.google.com/recaptcha/docs/display#js_api) (through a promise) which is "the ID of the newly created widget"

**Comment by pambuk** [comment]
Hi, I'll try to answer your questions later today (from what I remember waiting longer solved it).

**Comment by rderharo** [comment]
I followed the demo code and I get the same issue.

**Comment by TheSharpieOne** [comment]
@pambuk any update or code to post?

**Comment by TheSharpieOne** [comment]
Actually, I'm pretty sure reCaptcha's widget ids are just numbers, starting at 0, and going up by 1 each time a new one is instantiated.... so widgetId of 0 is fine and normal.

**Comment by TheSharpieOne** [comment]
@iambrosi @mtrias This can probably be closed as it is just how reCaptcha's widgetId's work and is not a defect
