### ISSUE TITLE
Uncaught Security Error -- Every Click

### ISSUE THREAD

**Issue by teracomp** [VividCortex/angular-recaptcha#41]
Everything appears to work well in my application. Thanks for the great work.

However, I now have this error on *every click* on my site after leaving the registration form.

Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "http://localhost".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

nz                 cb=gapi.loaded_0:46 
jz.send         cb=gapi.loaded_0:44 
Fz                cb=gapi.loaded_0:48 
(anonymous function)   cb=gapi.loaded_0:48 

Perhaps I need to unload the google api when moving off of the page? Watching the error count increase is not a good thing.

**Comment by TheSharpieOne** [comment]
The new API does not provide a way to remove/destroy the instance of recaptcha.  An ugly workaround is to manually remove the elements it adds to the page. This can easily be done on the `$destroy` event for the directive's scope.

I'll put a PR together when I get a sec.

**Comment by teracomp** [comment]
Fantastic!  Thanks!

**Comment by TheSharpieOne** [comment]
Well, that was easier than I thought.  Just added a part to remove the junk (including the iframe) that recaptcha adds.  This happens directly after a successfully click and for the `$destroy` event.

**Comment by teracomp** [comment]
Excellent work! Works perfectly!

**Comment by PelleWombit** [comment]
I have added the new lines of code but still getting the error.

Do you have any other ideas?

Are there any other changes that has to be made except those two in the directive?

**Comment by TheSharpieOne** [comment]
@PelleWombit can you add any additional information.  Make sure you are using the version with the edits and your cache has been cleared/disabled.

**Comment by PelleWombit** [comment]
Thanks for such quick response!

Yes I have added the edits to my angular-recaptcha.js

Same error as above:

cb=gapi.loaded_0:46 
Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "http://www.aktivskola.local".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
nz @ cb=gapi.loaded_0:46
jz.send @ cb=gapi.loaded_0:44
Fz @ cb=gapi.loaded_0:48
(anonymous function) @ cb=gapi.loaded_0:48

**Comment by dsge** [comment]
It might be connected to whether or not you are using a publicly accessible url. On my local development vhost I get the same "Uncaught SecurityError: Blocked a frame with origin [...]" error but on the stage and prod servers it works fine. All sites are using the same code with the same recaptcha key and they are added to the [recaptcha admin](https://www.google.com/recaptcha/admin#list) domain list properly.
