### ISSUE TITLE
"Permission denied to access property" after reload()

### ISSUE THREAD

**Issue by rderharo** [VividCortex/angular-recaptcha#44]
When I try to do `vcRecaptchaService.reload()` it seems to work but in my js console I get this every time I click my mouse or generally interact with my app in any way:

> Error: Permission denied to access property '10_1417377045946'

I found a solution here (https://groups.google.com/forum/#!topic/recaptcha/CZNuFp1ct_Y) but it's a hack: `$('.pls-container').remove();`.

I did try to pass a widgetId but because of #39 I was only getting widgetId = 0. Despite this, I don't see why I shouldn't be able to just call `reload()`.

Any ideas?

**Comment by TheSharpieOne** [comment]
You mean like [this](https://github.com/VividCortex/angular-recaptcha/blob/master/src/directive.js#L49) ?

**Comment by rderharo** [comment]
Ah, okay. But still, isn't that kind of an endorsement of a hack? I mean, it works, but for how long?

**Comment by TheSharpieOne** [comment]
Until Google fixes the issue.  You can file a bug for them to implement a way to remove/destroy the instance of recaptcha like the v1 API had.  For now, v2 doesn't have that ability and everything has to be a work-around or hack.

**Comment by rderharo** [comment]
Fair enough, thanks. Feel free to close this issue now or when the code is released.
