### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ericmdantas** [VividCortex/angular-recaptcha#48]
Hello.

I was thinking about creating some tests (with coverage) for this repository and I'd like to know what you think about it. So I know if I should carry on or not.

I'd also like to setup the integration with travis and coveralls, if you like the idea.

Anyway, here's what I got so far:

https://github.com/ericmdantas/angular-recaptcha

**Comment by mtrias** [comment]
Hey @ericmdantas 

We'd love to have that! If you feel like taking over, please do!

Thanks!

**Comment by ericmdantas** [comment]
Alright!

I'll submit a PR when I have most stuff done.

Closing this.
