### ISSUE TITLE
Build new version with spelling correction

### ISSUE THREAD

**Issue by RobzInadE** [VividCortex/angular-recaptcha#52]
Hello

Today when i bower install this module, it fetches 2.1.1 which still contains the cruicial misspelling. (https://github.com/VividCortex/angular-recaptcha/releases/tag/2.1.1)

Can you please build a new version fixing this? Otherwise using bower cannot be done with this project.

Regards

**Comment by mtrias** [comment]
It's done. Thanks for reporting this!
