### ISSUE TITLE
"Undefined is not a function"

### ISSUE THREAD

**Issue by sb89** [VividCortex/angular-recaptcha#54]
After verifying I'm not a robot, I'm receiving the following error:

    TypeError: undefined is not a function
    at cleanup (VM22475 angular-recaptcha.js:188)
    at VM22475 angular-recaptcha.js:152
    at angular.js:16223
    at e (angular.js:4905)
    at angular.js:5285

Which seems to be occurring at the following line:

     function cleanup(){
       // removes elements reCaptcha added.
        angular.element($document.querySelectorAll('.pls-container')).parent().remove();
      }

**Comment by iambrosi** [comment]
A PR has been opened for this at #53
