### ISSUE TITLE
selective validation

### ISSUE THREAD

**Issue by danielmedina** [VividCortex/angular-recaptcha#55]
In my app, i show recaptcha only if the user fails to login 3 times in sequence. Recaptcha is always loaded, but hidden using ng-hide. Because of this, i can't submit my form cause it always is invalid, since recaptcha is not marked (and it's not marked because it's hidden).

I can, simply don't validate recaptcha?

I saw that in issue #29 you validate if recaptcha is checked. Why you don't create a parameter to DON'T validate recaptcha?

**Comment by mtrias** [comment]
i had the same issue today, and fixed it using `ng-if` instead of `ng-show`

**Comment by TheSharpieOne** [comment]
Yes, I would suggest what @mtrias said for now. Perhaps, we can observe the visibility of the element to trigger the validation.

**Comment by mtrias** [comment]
Doing something to change the validation depending on the visibility, i think would be inconsistent with how other form inputs behave. For example if you have a required textbox input and you hide it, [the form will still be invalid](http://jsfiddle.net/rn006ewq/2/).

I think if we'd want to fix this, we should use the standard `ng-required`, but then showing the captcha without `ng-required`, would be silly imo. So my vote is to wontfix it.

**Comment by mtrias** [comment]
Just tagged as wontfix and closed. Please reopen if you guys disagree.

**Comment by TheSharpieOne** [comment]
Just to note: there is now a `required` attribute. Setting it to `false` (or a scoped variable which is `false`) will disable the validation.

Something like this will disable the validation when it is not showing:
```
<div vc-recaptcha
  key="'---- YOUR PUBLIC KEY GOES HERE ----'"
  ng-if="showReCaptcha"
  required="showReCaptcha">
</div>
```
