### ISSUE TITLE
Adding the google API javascript via requirejs

### ISSUE THREAD

**Issue by dngad** [VividCortex/angular-recaptcha#60]
Hello,

I wanted to know if anyone has any idea or example code as to how to call the api js via requirejs config?

I saw that its required to do the following:
script src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit" async defer script

So how can I add an onload parameter to the requirejs config such that everything works in harmony?

Kindly assist someone,
Thank you.

**Comment by dngad** [comment]
Alight so this was simple. I didn't realize adding ? parameters would work so well with requirejs since it has the habit of adding .js extention. #Closed

**Comment by jdoc** [comment]
Hi, @kryptodev ,
I have a question, is the vcRecaptchaApiLoaded function a global function in this case?
Thanks
