### ISSUE TITLE
What do I send to the server as the challenge?

### ISSUE THREAD

**Issue by mikepc** [VividCortex/angular-recaptcha#61]
In order to validate the captcha server side, I need to pass a challenge, what variable/function will give me the correct challenge data?

**Comment by mikepc** [comment]
I recognize that the latest version of Recaptcha doesn't require challenge, but all of the latest recaptcha node modules require the challenge field. What am I missing?

**Comment by jackkum** [comment]
You're need send post request to url https://www.google.com/recaptcha/api/siteverify

from here https://developers.google.com/recaptcha/docs/verify
