### ISSUE TITLE
Reload is broken

### ISSUE THREAD

**Issue by kemins** [VividCortex/angular-recaptcha#62]
seems like reload of captcha is broken due to: "angular.element($document[0].querySelectorAll('.pls-container')).parent().remove();"

function cleanup(){
                  // removes elements reCaptcha added.
                  angular.element($document[0].querySelectorAll('.pls-container')).parent().remove();
                }

**Comment by TheSharpieOne** [comment]
What is the error you are seeing?

**Comment by bobisjan** [comment]
Hi, I just hit the same issue, there is no error to see, but I've find that calling `cleanup()` function [here](https://github.com/VividCortex/angular-recaptcha/blob/master/src/directive.js#L50) breaks reloading (just comment this line out and reloading works again).
