### ISSUE TITLE
Can't reload recaptcha after submitting invalid form

### ISSUE THREAD

**Issue by tam-vo** [VividCortex/angular-recaptcha#63]
I added recaptcha widget to my login and whether user submitted wrong credentials, I tried to reload recaptcha by using `vcRecaptchaService.reload($scope.widgetId);` (like an example) but the recaptcha is  not reloaded and I also received a message in browser console: 
```
Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "https://xxx.com". Protocols, domains, and ports must match.
```
thought both site using https protocol already. 
Please let me know any suggestion.

**Comment by tam-vo** [comment]
Anyone here? please help me this issue,

**Comment by tam-vo** [comment]
Thanks for your response. It worked.

**Comment by AquilaSagitta** [comment]
I'm still having this issue. Running https and still get `Uncaught SecurityError: Blocked a frame with origin ... Protocols, domains, and ports must match.`
