### ISSUE TITLE
Dynamically change language

### ISSUE THREAD

**Issue by gekalogiros** [VividCortex/angular-recaptcha#66]
Is there any way to dynamically change the language of the captcha by using this module???

**Comment by ratonlarvor** [comment]
+1

**Comment by TheSharpieOne** [comment]
I'm not sure if this ability to even supported by Google reCaptcha.  From the [docs](https://developers.google.com/recaptcha/docs/display#config) it looks like it is set in the script tag's URL, and if not provided it will auto-detect the user's default language.
The script it loads will load the actual script, which is different based on the language (each script has the verbiage "hard-coded" into the script in the language).
I'm not 100% sure if you can even load multiple reCaptcha scripts on the same page (or if it will complain that its already loaded), but I am sure that if you could, they will clobber each-other.  `window.grecaptcha` would be whichever language loaded last.

**Comment by ratonlarvor** [comment]
Hi,

I added the following directive to manage the language. 
```javascript
.directive('script', function($parse, $rootScope, $compile) {
        return {
            restrict: 'E',
            scope: {
                lang: '@ngLang'
            },
            link: function(scope, element, attr) {
                  if (attr.ngSrc) {
                       var domElem = '<script id="captchaSrc" src="'+attr.ngSrc+'&hl='+scope.lang+'" async defer></script>';
                       $(element).append($compile(domElem)(scope));
                   }
                });
            }
        };
    });
```
Then import your script.
```
<script ng-src="//www.google.com/recaptcha/api.js?render=explicit&onload=vcRecaptchaApiLoaded" ng-lang="{{ language.use() }}" async defer></script>
```
It works fine but I still need to refresh my application when I change dynamically the language (I'm using angular-translate).

Hope this can help

**Comment by lluiscanals** [comment]
Are you going to add this in the next release?

**Comment by iambrosi** [comment]
I don't think we should add this functionality as part of this package, as it's not responsible of loading the recaptcha's api.
Closing this as wontfix.

**Comment by toedoro** [comment]
Hi @iambrosi i just wanted to reach-out for any help! 
is there a way that we can update or change the language for the **vc-recaptcha** that is being set by the user from a certain dropdown of all the available languages. maybe i miss something since it doens't changed it's content from **vc-recaptcha**
HTML
```
<div
        vc-recaptcha
        ng-model="customer.captcha"
        type="'image'"
        key="system.KEY"
        lang="captchaLanguage.isoCode"
    ></div>
```
Angular.controller
```
$scope.$watch('language', function(language) {
   $scope.captchaLanguage = language;
});
```
