### ISSUE TITLE
Awesome Library!

### ISSUE THREAD

**Issue by rahil471** [VividCortex/angular-recaptcha#68]
Hey guys this a great work from your part to make reCaptcha integration easier for Angular Projects.
Didn't knew where to reach out to you guys so posting it here.

I've also written a tutorial which uses this library, along with a server side example.

http://code.ciphertrick.com/2015/05/19/google-recaptcha-with-angularjs/

Thanks for this awesome library. :)

**Comment by mtrias** [comment]
Hey! thank you for writing that blog post.

Kudos to all the contributors who made it a great tool!

Thanks! :beer:
