### ISSUE TITLE
When reloading, the validity is not set to false

### ISSUE THREAD

**Issue by alexp2012** [VividCortex/angular-recaptcha#69]
I noticed that when I first load a page with the widget, the validity of "recaptcha" is set to false.

I fill in the form (including captcha), I make an asynchronous submit using angular, I get an error from the server, I reload the widget (vcRecaptchaService.reload). This does not set its validity to false again, so there's a small inconsistency.

**Comment by richscan** [comment]
I'm running into the same issue. On server side validation fail I want to "reset" reCaptcha to that the form indicates it's not valid. Calling vcRecaptchaService.reload() does not achieve this. Is there another path I can take to indicate the captcha is not valid?

**Comment by TheSharpieOne** [comment]
Seems like [this comment](https://github.com/VividCortex/angular-recaptcha/blob/96fe58576c83f295e9e195482d18d3986ae7c49a/src/service.js#L78-L79) is not true.
