### ISSUE TITLE
firefox vs. chrome

### ISSUE THREAD

**Issue by stevenpkent** [VividCortex/angular-recaptcha#71]
Is anyone seeing this issue?  The widget is working in Ffox but not in Chrome?

**Comment by jackkum** [comment]
Works weel.

**Comment by iambrosi** [comment]
Hello @stevenpkent! I can see the widget working both in Firefox and Chrome. 
Do you see any errors in the Chrome console? What version of _angular-recaptcha_ are you using?

**Comment by stevenpkent** [comment]
Hi @iambrosi, no there were no errors in chrome console.  The widget had been working fine in chrome.  The widget version is angular-recaptcha build:2015-04-28.

I had 2 other users verify the same result as me: did not work in chrome, worked in firefox.  The version of chrome is Version 43.0.2357.134 m.

For now I have commented the widget out.  But we do need it, so if you want me to work with you to diagnose, I am willing to do that.

**Comment by mtrias** [comment]
Can you explain what you see? Do you see the captcha but it doesn't work? is it not appearing at all?

**Comment by stevenpkent** [comment]
Sure.  Yes I see the widget.  But the checkbox has no reaction to being clicked.

If you want to tell me the specific things you are looking for I will try to provide them.  Or even do a screenshare, that would be fine with me.

**Comment by mtrias** [comment]
A shot in the dark: could it be possible that you have a transparent element that is on top of the captcha and that is receiving the click event?

Do you have a public URL where we can see it ?

**Comment by stevenpkent** [comment]
No on the transparent element.

And no on the public URL.  Because it was not working in chrome for us, I removed it from the site.

I just have it on my local machine currently.

**Comment by mtrias** [comment]
@stevenpkent I just crafted a very simple demo of recaptcha hosted inside github pages. Can you try here please?

http://vividcortex.github.io/angular-recaptcha/

**Comment by stevenpkent** [comment]
Nice job @mtrias.  Your demo works perfectly in every OS/Browser test I did.

**Comment by stevenpkent** [comment]
I will compare the code in your demo with what I have in my site.  Thanks again.

**Comment by mtrias** [comment]
Awesome! you almost scared us xD.

cheers :beer:

**Comment by stevenpkent** [comment]
Hey guys our frontend design guy just fixed our issue.  Here's what it was: there was a div over the checkbox with a CSS class of 'fade' on it.  That div was receiving the click event.  He made the fade class have pointer-event of none.  Now we can click the checkbox.

**Comment by mtrias** [comment]
Awesome! Thanks for the update.

Regarding the misterious `<div>`, I don't think we are adding that div (or any other markup) to the captcha. It would be nice to reproduce your error in an isolated test html and see what causes it.
