### ISSUE TITLE
Invalid ReCAPTCHA client id: undefined"

### ISSUE THREAD

**Issue by ozziest** [VividCortex/angular-recaptcha#78]
When i use the service like that, i see the error.

```
vcRecaptchaService.getResponse()
```

But I have checked the directive with `on-create` event, captcha was loading and I see the captcha on the screen. I can use it but i can't get the response with `getResponse()`.

What is the problem?

**Comment by frostshoxx** [comment]
Hello, I had the same problem as well. Looks like it has to do with angular trying to include the script more than once

<script src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit"
        async defer></script> 

reference: http://stackoverflow.com/questions/27574733/how-to-reload-the-google-recaptcha-widget-after-user-submits-invalid-inputs


I'm not quite sure what's the best way to handle this yet, though.

**Comment by frostshoxx** [comment]
Silly me. I'm supposed to get the response from the input param directly instead of using vcRecaptchaService.getResponse()


        vm.setResponse = function (response) {
            // send the `response` to your server for verification.
            vm.captchaResponse = response;
            vm.canSubmit = true;
        };

It's all good now
