### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by derekr** [VividCortex/angular-recaptcha#79]
Seems the version on NPM is out of date (currently `1.0.1`). Mind publishing the latest? Thanks!

**Comment by meanJim** [comment]
:+1:

**Comment by iambrosi** [comment]
It seems there's an issue in in NPM. We'll take a look and restore the latest versions.

**Comment by iambrosi** [comment]
This has been fixed and now version 2.2.5 is available on NPM.

**Comment by derekr** [comment]
Awesome! Thanks so much.
