### ISSUE TITLE
Subsequent getResponse call when challenge is not attempted causes crash

### ISSUE THREAD

**Issue by parthiv108** [VividCortex/angular-recaptcha#81]
Hi, 
Firstly great work on the reCapta module...works well except for the following case:
If i submit a form without "checking" the box for the 2nd time I get the following error when trying to get the response:
<code>
TypeError: Cannot read property 'value' of null
    at Object.Pn [as getResponse] (https://www.gstatic.com/recaptcha/api2/r20150901234645/recaptcha__en_gb.js:313:279)
    at Object.app.service.$q.getResponse (http://localhost:8080/jamApp/app/lib/angular-recaptcha/release/angular-recaptcha.js:96:34)
    at Scope.$scope.registerUser (http://localhost:8080/jamApp/app/components/user/registerUserCtrl.js:14:43)
    at Parser.functionCall (http://localhost:8080/jamApp/app/lib/angular/angular.js:10903:21)
    at ngEventDirectives.(anonymous function).$rootScope.compile.element.on.callback (http://localhost:8080/jamApp/app/lib/angular/angular.js:19259:17)
    at Scope.promises.$get.Scope.$eval (http://localhost:8080/jamApp/app/lib/angular/angular.js:12811:28)
    at Scope.promises.$get.Scope.$apply (http://localhost:8080/jamApp/app/lib/angular/angular.js:12909:23)
    at HTMLFormElement.<anonymous> (http://localhost:8080/jamApp/app/lib/angular/angular.js:19264:23)
    at http://localhost:8080/jamApp/app/lib/angular/angular.js:2853:10
    at forEach (http://localhost:8080/jamApp/app/lib/angular/angular.js:325:18)
</code>

It works fine if I refresh the page. Its just that I get the error on subsequent form submission (e.g. after navigating to another page and coming back).

**Comment by TheSharpieOne** [comment]
The error looks to be originating from Google's reCaptcha script.
![image](https://cloud.githubusercontent.com/assets/664714/9676366/60b88f8a-5298-11e5-9372-e5134a3d204d.png)

Can you share your registerUserCtrl.js code to help get to the bottom of this?

**Comment by parthiv108** [comment]
<code>
/**
 * Created by Parthiv on 21/08/2015.
 */



controllers.controller('registerUserController', function($scope, $location, registerUserService, vcRecaptchaService){

    $scope.successfulRegisterFlag= false;
    

    $scope.registerUser = function(form, user){
        console.log("1 going to register user, form = "+form+", valid= "+form.$valid);
        var response = vcRecaptchaService.getResponse();
        console.log("2 response = "+response);
        if(form==undefined || !form.$valid){
            return;
        }

        user.captchaResponse=response;
        console.log("going to register user = "+ JSON.stringify(user)+", form status= "+form.$valid);
        registerUserService.saveUser(user,
            function success(data){
                console.log("saved successfully");
                $scope.resultMsg = "You're almost done! Please check your e mail to complete your registration";
                $scope.alertStatus = "alert-success";
                $scope.successfulRegisterFlag = true;


            },function failure(errorMsg){
                //alert("An error has occurred when saving the user details. Please try again later");
                $scope.alertStatus = "alert-danger"; //css to show alert in respective colour based on state
                $scope.resultMsg = errorMsg;
                //$scope.resultMsg = "An error has occurred when saving the user details. Please try again later";
                console.log("error= "+errorMsg);
            });
    }

//    $scope.testUsername = function(){
//        registerUserService.checkUsernameUnique($scope.user.username,
//        function success(){
//            console.log("in success...duplicate user found");
//            $scope.duplicateUsernameMsg = "This Username has been taken. Please choose another one";
//
//        },
//        function failure(){
//            console.log("in failure..no duplicates, so don't do anything");
//            $scope.duplicateUsernameMsg=null;
//        });
//
//
//    }
    $scope.testUsername = function(){
        registerUserService.checkUsernameUnique($scope.user.username)
            .$promise.then(
            function success(){
                console.log("in success...duplicate user found");
                $scope.duplicateUsernameMsg = "This Username has been taken. Please choose another one";

            },
            function failure(){
                console.log("in failure..no duplicates, so don't do anything");
                $scope.duplicateUsernameMsg=null;
            });


    }

});

//Directive to check for a username
directives.directive('isUsernameUnique',['registerUserService',function(registerUserService){
    return{
        require:'ngModel',
        restrict:'A',
        link:function(scope,element,attrs,ngModel){
                console.log("in isUsernameUnique directive");
                element.bind('blur', function (e) { //fire link function on blur event from the input field
                    if (!ngModel || !element.val()) return; //exit if no ng-model or value present on element
                    //var keyProperty = scope.$eval(attrs.wcUnique);
                    var currentValue = element.val();
                    registerUserService.checkUsernameUnique(currentValue)
                        .$promise.then(function () {
                            //Ensure value that being checked hasn't changed
                            //since the Ajax call was made
                            if (currentValue == element.val()) {
                                ngModel.$setValidity('unique', false);
                            }
                        }, function () {
                            //Probably want a more robust way to handle an error
                            //For this demo we'll set unique to true though
                            ngModel.$setValidity('unique', true);
                        });
                });



        }
    }
}]);
</code>

**Comment by TheSharpieOne** [comment]
Just as I suspected, the issue is when you call `var response = vcRecaptchaService.getResponse();`

`getResponse()` has a argument that must be passed to it, the widgetId, when multiple recaptcha widgets are registered/on the same page.  Since you have a SPA, even though the first widget is no longer there, it is still registered in Google's code.

You'll have to use the `on-create` callback to get the widgetId to use when calling `getResponse(widgetId)`; OR you an use the `on-success` callback to get the response directly, when it id set.

**Comment by parthiv108** [comment]
Great Stuff!  I got it working after using the on-success callback. Thank you very much.

**Comment by prudhvi-php** [comment]
For me it's not worked, my recaptcha code is,
`<div vc-recaptcha key="my key here" ng-model="letter.myRecaptchaResponse" on-create="setRecaptchaId(widgetId)"> </div>` and my code in controller is
```
$scope.setRecaptchaId = function(widgetId) {
    $scope.recaptchaId = widgetId;
    return;
};
$scope.letter.mresponse = vcRecaptchaService.getResponse($scope.recaptchaId);
```
any suggestion.

**Comment by prudhvi-php** [comment]
i came to know that on-create and on-success listeners are not working properly. At least for me they are not working as required but not getting why..

**Comment by TheSharpieOne** [comment]
@prudhvi-php you should not be setting the value of the recaptcha inside of scope yourself, it does that for you when the value is available.
