### ISSUE TITLE
getResponse() not working when instantiated again

### ISSUE THREAD

**Issue by elijahb** [VividCortex/angular-recaptcha#83]
Hi,
I'm using it on a modal box, working fine the first time, but if the modal box is opened a second time despite it's shown it throws error *Cannot read property 'value' of null* when calling to `vcRecaptchaService.getResponse()` . 

The modal box is called using Angular Bootstrap UI, so it uses a controller and a template, where the recaptcha tag is placed.

**Comment by jackkum** [comment]
@elijahb this can help: https://github.com/VividCortex/angular-recaptcha/issues/81

**Comment by elijahb** [comment]
Thanks @jackkum , it was it ! Sorry that I didn't check previous issues.
