### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by romelgomez** [VividCortex/angular-recaptcha#84]
Hi VividCortex,

After passing the reCaptcha, then wait some seconds until is invalidated, 
the error happens when i try again pass the captcha. 

![screenshot from 2015-09-21 10 31 11](https://cloud.githubusercontent.com/assets/2358251/9984328/3609703e-5fdf-11e5-9f0d-1a7beeb56f7e.png)

**Comment by mtrias** [comment]
+1 Good catch!

**Comment by wniehof** [comment]
I noticed that the solution of romelgomez works. However the message: "captcha verification expired" is also removed. It just loads a new  recaptcha widget.

**Comment by romelgomez** [comment]
Yes, that's what happens, exactly as described by @wniehof. When the captcha expire, a new captcha is loaded, you never see the 'captcha verification expired', in this point we can say that is just a patch.
