### ISSUE TITLE
How to use the "Secure Token" option

### ISSUE THREAD

**Issue by roblav96** [VividCortex/angular-recaptcha#87]
I'm integrating recaptcha into my cordova application and since the domain being used will be the users phone, I need to use the ["Secure Token" option](https://developers.google.com/recaptcha/docs/secure_token).

Any idea how to implement this with your angular module?

**Comment by felipe-pereira** [comment]
+1

**Comment by kyvkri** [comment]
+1

**Comment by felipe-pereira** [comment]
Server side token generation issues, plus poor reCaptcha UX lead us to remove reCaptcha from our API, so I'm taking back my +1 :)

**Comment by magnusharaldsenamundsen** [comment]
+2

**Comment by fkammer** [comment]
+1

**Comment by abd2561024** [comment]
+1

**Comment by fkammer** [comment]
I just opened a PR to support secure tokens: #100

If you want to use it before it's merged, use
`bower install --save 'https://github.com/fkammer/angular-recaptcha.git#feature-stoken-support'`
