### ISSUE TITLE
how to Reset Captcha

### ISSUE THREAD

**Issue by RajMondaz** [VividCortex/angular-recaptcha#88]
i am using captcha while registration..
after registration successful i have to make Check box Unchecked. how to do this..?

**Comment by mtrias** [comment]
Can i as why would you want to do this?

Once the captcha is resolved (one time), you know the user is a human, so you don't need the captcha there anymore.

**Comment by RajMondaz** [comment]
i am using captcha for registration after registration is done.
i have to reset the form , so there i have to reset the captcha also..

**Comment by mtrias** [comment]
Why not removing the captcha once the registration is done?

**Comment by TheSharpieOne** [comment]
You can only validate the captcha response with Google once, then it is invalidated.  You can reset it via `vcRecaptchaService.reload(widgetId)`.

https://github.com/VividCortex/angular-recaptcha/blob/master/src/service.js#L62-L70

**Comment by mtrias** [comment]
Is this something we still need to address, or can we close this ?

**Comment by CyrilleGuimezanes** [comment]
FYI works for me with: vcRecaptchaService.reload(widgetId). 

Regards,

**Comment by mtrias** [comment]
Thanks @CyrilleGuimezanes. Let's close this one then.

**Comment by AndersBillLinden** [comment]
Is the id mandatory?

**Comment by TheSharpieOne** [comment]
Yes and no. It is technically not mandatory, recaptcha will default to the first widget, 0. But if you load multiple widgets (in a SPA, this happens a lot, even if you only have one widget as the one widget can load multiple times itself) chances are widget 0 will no longer be on the page and that will cause an error. It's best to always supply the widget id.

**Comment by AndersBillLinden** [comment]
There should be a reloadAdd method and the id:s could be omitted.
