### ISSUE TITLE
unable to figure out the site-key 

### ISSUE THREAD

**Issue by Webinator2129** [VividCortex/angular-recaptcha#89]
Hi, I am using angular-recaptcha + Jinja2 which both uses the {{format}} templates values, the solution used to work before but now stopped. trying to debug and print all values: site-key, response, url and replies and I am getting **invalid-input-secret** response

tried to print  **site-key** value processed by vcRecaptchaService but there are no function returning this value, need to verify if the site-key is correct

**Comment by leosuncin** [comment]
Try this to debug
```html
<!-- Begining of your form -->
<span>site-key: {{ reCaptchaSiteId }}</span>
<div vc-recaptcha key="reCaptchaSiteId"></div>
<!-- Rest of your form -->
```

**Comment by TheSharpieOne** [comment]
@Webinator2129 Any update on this issue?

**Comment by mtrias** [comment]
Closing as it was inactive for too long. Reopen if this issue is not fixed.
