### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lastElementChild' of null

### ISSUE THREAD

**Issue by tobiasbrenner** [VividCortex/angular-recaptcha#90]
After a correct vcRecaptchaService.reload fn call with an existing widgetId this error:
"Uncaught TypeError: Cannot read property 'lastElementChild' of null"
will appear after every scroll event.
![error](https://cloud.githubusercontent.com/assets/458177/11063114/a46a875a-87b4-11e5-8362-99f2c68bc121.PNG)

**Comment by nblumhardt** [comment]
We too are experiencing this and are digging in deeper - any clues you've uncovered would be appreciated :-)

**Comment by A-P** [comment]
It looks like this is a bug in Google's JS (missing a null check). I was seeing the same thing in recaptcha__en.js and tried debugging with only the recaptcha js and vanilla js code to .render and  .reset - no Angular at all. The same error occurs.

**Comment by haduythuan** [comment]
Don't worry about this issue. Recaptcha Support Guy from Google promised this will be resolved in their next release.

https://groups.google.com/forum/#!msg/recaptcha/lmMdUo3JR-0/p112nO-lAQAJ

**Comment by nblumhardt** [comment]
Thanks @haduythuan !

**Comment by TheSharpieOne** [comment]
Any update on this? Is this still an issue?

**Comment by mtrias** [comment]
I'm closing this as it seems nothing needs to be done. Please tell me if i'm wrong.
