### ISSUE TITLE
reCaptcha window not responsive

### ISSUE THREAD

**Issue by neverendingqs** [VividCortex/angular-recaptcha#92]
When viewing on a mobile device, I encounter the problem outlined here: https://www.geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

Basically, the reCaptcha is too big and goes off screen.

Would it be possible to incorporate the solution outlined in the same link?

**Comment by RopoMen** [comment]
recaptcha is rendered inside iframe so if you are using Bootstrap you can use http://getbootstrap.com/components/#responsive-embed

If you are not using Bootstrap you can see how Bootstrap is doing it from [here](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L5796)

**Comment by neverendingqs** [comment]
@RopoMen did you mean something like this?

Doing this causes the reCaptcha window to disappear:

    <div class="form-group col-md-12">
	  <div class="embed-responsive">
        <div vc-recaptcha key="'mykey"" on-success="setResponse(response)" on-expire="cbExpiration()"></div>
	  </div>
    </div>

Doing this causes it to show up, but with it cut off:

    <div class="form-group col-md-12">
	  <div class="embed-responsive embed-responsive-4by3">
        <div vc-recaptcha key="'mykey"" on-success="setResponse(response)" on-expire="cbExpiration()"></div>
	  </div>
    </div>

**Comment by TheSharpieOne** [comment]
The solution outlined in the link provided in the original post is something which you will need to do in your project.
IMHO styling reCaptcha (besides the `theme` attribute) is outside of the scope of this project.

**Comment by mtrias** [comment]
Closing as wontfix. Let us know if there are more thoughts on this.
