### ISSUE TITLE
Captcha not loading at first time

### ISSUE THREAD

**Issue by rluders** [VividCortex/angular-recaptcha#93]
Hello,

I'm having some problem to load the captcha at first time on my page. Sometimes it's at first time it works and sometimes only after reload the page.

Not browser related. Tested on: Firefox and Chrome.
No console errors.
No resource loading erros at network.

Packages:
angular:~1.4.8
angular-recaptcha:~2.2.5

Any ideas?

**Comment by rluders** [comment]
Solved. API Javascript must be loaded using:

<script src="https://www.google.com/recaptcha/api.js?onload=vcRecapthaApiLoaded&render=explicit&hl=en" async defer></script>

**Comment by manuel-di-iorio** [comment]
I also have this problem, please @rluders how do you fixed this issue?

**Comment by lakshbhutani** [comment]
I also have this problem, please tell me  @rluders ,the above solution is not working.

**Comment by rluders** [comment]
@manuel-di-iorio @lakshbhutani well... It was in 2015. I have no idea. I'm not using AngularJS anymore.

**Comment by shanmicheal25** [comment]
I have some problem  load the captcha at first time on my page, once refresh page I able to see captcha.
I configure in index.html 
<script src='https://www.google.com/recaptcha/api.js'>

**Comment by abdullahir** [comment]
i also tried this,but not working
