### ISSUE TITLE
Choose images only works first time in chrome

### ISSUE THREAD

**Issue by jvcjunior** [VividCortex/angular-recaptcha#94]
Hi,
I am using "angular-recaptcha": "~2.2.5" with chrome. When I access the page for the first time and use the recaptcha it works fine. Next time I tried to click on the checkbox the component is marked as checked and didn't show the modal with images to choose. Is this a configuration problem? What am  I doing wrong? 

I am using like this: 

```
 <div class="form-group">
        <div 
        vc-recaptcha
        data-size="compact"
         key="'6LdLZhETAAAAADzgBNW572QrhPVmj6B_t2LD-zbP'">
        </div>
  </div>
```

**Comment by TheSharpieOne** [comment]
This is how Google's reCaptcha works.  Google's reCaptcha will use unknown logic to determine if you are human or not. Depending on how sure it is, reCaptcha will either display a challenge (such as images) or simply accept you are human (by checking the box without a challenge).  Sometimes it will let you just check the box, other times it will challenge you.

**Comment by jvcjunior** [comment]
I did not know that. Thank you very much @TheSharpieOne
