### ISSUE TITLE
Feature request - Set site-key in a service provider instead of every view

### ISSUE THREAD

**Issue by leosuncin** [VividCortex/angular-recaptcha#98]
Maybe you can add the possibility to config "site key" in one place instead on every view in order to avoid a mistype error, by example:
app.js
```js
angular.module('appName', ['vcRecaptcha'])
.config(['vcRecaptchaProvider', function(vcRecaptcha) {
  vcRecaptcha.setSiteKey('--Site key gos here--');
}]);
```
controller.js
```js
angular.module('appName')
.controller('Controller', [
  '$scope',
  'vcRecaptchaService',
  function($scope, vcRecaptchaService) {
    $scope.submitForm = function() {
      var response = vcRecaptchaService.getResponse();
    }
  }
])
```
view.html
```html
<form role="form" ng-submit="submitForm()">
  <div vc-recaptcha></div>
  <button type="submit">Send</button>
</form>
```

**Comment by TheSharpieOne** [comment]
I typically set it a higher up scope or even `$rootScope` then reference it using the controllerAs name such as `app.recaptchaConfig.key` or `$rootScope.recaptchaConfig.key`.
But yes, it would be nice and more preferable to use a provider to set the key and possibly over default values.

**Comment by mtrias** [comment]
:+1:
